spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production
logging:
  file:
    name: logs/vets-service.log
management:
  endpoint:
    logfile:
      external-file: logs/vets-service.log
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
