spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    gateway:
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
logging:
  file:
    name: logs/api-gateway.log
management:
  endpoint:
    logfile:
      external-file: logs/api-gateway.log
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: default

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
