name: Deploy to Azure Spring Apps
on:
  workflow_dispatch:
    inputs:
      directory:
        type: choice
        description: Which directory to deploy
        options:
          - spring-petclinic-admin-server
          - spring-petclinic-api-gateway
          - spring-petclinic-customers-service
          - spring-petclinic-vets-service
          - spring-petclinic-visits-service
        required: true
      app-name:
        type: choice
        description: The Azure Spring Apps app name
        options:
          - admin-server
          - api-gateway
          - customers-service
          - vets-service
          - visits-service
        required: true

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with artifact
    environment: AZURE_SPRING_APPS_ENVS
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: maven build, clean
        run: |
          mvn clean package

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy to production with artifact
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ vars.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: ${{ vars.AZURE_SPRING_APPS_SERVICE_NAME }}
          app-name: ${{ github.event.inputs.app-name }}
          use-staging-deployment: false
          package: ${{ github.workspace }}/${{ github.event.inputs.directory }}/*.jar
